version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: ./backend/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: antoncp/foodgram_backend:latest
    env_file: ./backend/.env
    volumes:
      - static:/foodgram_static/
      - media:/app/media/
    depends_on:
      - db
  frontend:
    image: antoncp/foodgram_frontend:latest
    volumes:
      - ./frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/templates/default.conf.template
      - ./frontend/build:/usr/share/nginx/html/
      - static:/foodgram_static/
      - media:/app/media/